from arcade_machine_sdk import GameMeta

# Lista de metadata de ciertos juegos que tienen metadata incorrecta

meta_replacements: dict[str, GameMeta] = {}

meta_replacements["street-fighter"] = (GameMeta()
                                       .with_title("Street Fighter 2")
                                       .with_description("Clásico juego de pelea arcade")
                                       .with_release_date("10/02/2026")
                                       .with_group_number(3)
                                       .add_tag("Pelea")
                                       .add_author("Keiber Medina")
                                       .add_author("Juan Rodriguez"))

meta_replacements["snake"] = (GameMeta()
                              .with_title("Snake")
                              .with_description("Juego Clasico de la Serpiente")
                              .with_release_date("2026-02-27")
                              .with_tags(["arcade", "snake", "retro"])
                              .with_group_number(5)
                              .with_authors(["Hemberth Garcia", "Eduardo Diaz"]))

meta_replacements["bomberman"] = (GameMeta()
                                  .with_title("Bomberman")
                                  .with_description("Juego arcade estilo Bomberman")
                                  .with_release_date("2026")
                                  .with_group_number(7)
                                  .add_tag("Arcade")
                                  .add_author("Katherin Martinez")
                                  .add_author("Rene Franco"))

meta_replacements["centipede"] = (GameMeta()
                                  .with_title("Centipede")
                                  .with_description("Classic")
                                  .with_release_date("2/02/2026")
                                  .with_group_number(9)
                                  .add_tag("Shooter")
                                  .add_author("Juan Simancas")
                                  .add_author("Gabriel Garanton"))

meta_replacements["galaga"] = (GameMeta()
                               .with_title("Galaga")
                               .with_description("Clásico juego shooter Galaga")
                               .with_release_date("17/02/2026")
                               .with_group_number(3)
                               .add_tag("Arcade")
                               .add_tag("Shooter")
                               .add_tag("Toad")
                               .add_author("Genesis Bentancourt")
                               .add_author("Luis Lameda"))

meta_replacements["jumper"] = (GameMeta()
                               .with_title("Jumper")
                               .with_description("Dino Arcade")
                               .with_release_date("2024-05-26")
                               .with_tags(["arcade", "retro", "runner", "pixel-art"])
                               .with_group_number(4)
                               .with_authors(["Michel larez", "Victor Coa"]))

meta_replacements["flappy-bird"] = (GameMeta()
                                    .with_title("Flying Duck")
                                    .with_description("Esquiva las tuberías y demuestra tus reflejos con el pato más audaz.")
                                    .with_release_date("17/02/2026")
                                    .with_group_number(6)
                                    .add_tag("Arcade")
                                    .add_tag("Flyer")
                                    .add_tag("Jump")
                                    .add_author("Antonella Fermin")
                                    .add_author("Alexandra Cedeno"))

meta_replacements["mario-bros"] = (GameMeta()
                                   .with_title("Super Mario Bros")
                                   .with_description("Juego de prueba")
                                   .with_release_date("10/02/2026")
                                   .with_group_number(8)
                                   .add_tag("Plataforma")
                                   .add_author("Anelissa Espin")
                                   .add_author("Erick Gomez")
                                   .add_author("Abelardo Drika"))

meta_replacements["frogger"] = (GameMeta()
                                .with_title("Frogger")
                                .with_description("Juego de rana")
                                .with_release_date("16/12/2025")
                                .with_group_number(9)
                                .add_tag("Plataforma")
                                .add_author("Juan Fernandez")
                                .add_author("Daniela Suniaga"))
